package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
)

type LibraryGenerator struct{}

func NewLibraryGenerator() *LibraryGenerator {
	return &LibraryGenerator{}
}

func (g *LibraryGenerator) GenerateLibrary() error {
	scraper := PayloadScraper{}
	outputDir, err := generatedOutputDir()
	if err != nil {
		return err
	}

	apiMethods, err := scraper.GetArraysPayloadsFromWebsite()
	if err != nil {
		return err
	}

	filesMap := map[string]bool{}
	for _, method := range apiMethods {
		if len(method) == 0 || !strings.Contains(method[0], ".") {
			continue
		}
		group := strings.Split(method[0], ".")[0]
		filesMap[group] = true
	}
	groups := make([]string, 0, len(filesMap))
	for group := range filesMap {
		groups = append(groups, group)
	}
	slices.Sort(groups)

	if err := os.MkdirAll(outputDir, os.ModePerm); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	for _, methodsGroup := range groups {
		className := toCamelCase(methodsGroup)
		builder := &strings.Builder{}

		builder.WriteString("// Code generated by goxploit msfrpc LibraryGenerator. DO NOT EDIT.\n\n")
		builder.WriteString("package metasploit\n\n")
		builder.WriteString("import (")
		builder.WriteString("\n\t\"errors\"")
		builder.WriteString("\n\t\"fmt\"")
		builder.WriteString("\n\t\"github.com/arisinghackers/goxploit/pkg/msfrpc\"")
		builder.WriteString("\n)\n\n")
		builder.WriteString(fmt.Sprintf("type %s struct {\n\t*msfrpc.MsfRpcClient\n}\n\n", className))

		builder.WriteString(fmt.Sprintf("func New%s(client *msfrpc.MsfRpcClient) *%s {\n", className, className))
		builder.WriteString(fmt.Sprintf("\treturn &%s{client}\n", className))
		builder.WriteString("}\n\n")

		groupMethods := [][]string{}
		for _, method := range apiMethods {
			if len(method) == 0 || !strings.Contains(method[0], ".") {
				continue
			}
			if strings.Split(method[0], ".")[0] != methodsGroup {
				continue
			}
			groupMethods = append(groupMethods, method)
		}
		slices.SortFunc(groupMethods, func(a, b []string) int {
			return strings.Compare(a[0], b[0])
		})

		for _, method := range groupMethods {
			rawMethod := strings.SplitN(method[0], ".", 2)[1]
			funcName := toCamelCase(rawMethod)

			params := []string{}
			args := []string{fmt.Sprintf(`"%s"`, method[0])}
			requiresAuth := false

			for _, val := range method[1:] {
				param := strings.Trim(val, "<>")
				if strings.Contains(val, "<") {
					if strings.Contains(param, "token") {
						requiresAuth = true
						continue
					}
					args = append(args, param)
					params = append(params, fmt.Sprintf("%s string", param))
					continue
				}

				if methodsGroup == "console" && strings.EqualFold(val, "inputCommand") {
					args = append(args, fmt.Sprintf("%s+\"\\n\"", val))
				} else {
					args = append(args, val)
				}
				params = append(params, fmt.Sprintf("%s string", val))
			}

			builder.WriteString(fmt.Sprintf("func (c *%s) %s(%s) (map[string]interface{}, error) {\n", className, funcName, strings.Join(params, ", ")))
			if requiresAuth {
				builder.WriteString(fmt.Sprintf("\tresp, err := c.AuthenticatedRequest(%s)\n", buildArgsString(args)))
			} else {
				builder.WriteString(fmt.Sprintf("\tresp, err := c.MsfRequest(%s)\n", buildArgsString(args)))
			}
			builder.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			builder.WriteString("\tif result, ok := resp[\"result\"]; ok && result == \"failure\" {\n")
			builder.WriteString("\t\treturn nil, errors.New(\"Unprocessable Content\")\n\t}\n")
			builder.WriteString("\tif errMsg, ok := resp[\"error_message\"]; ok {\n")
			builder.WriteString("\t\treturn nil, fmt.Errorf(\"%v\", errMsg)\n\t}\n")
			builder.WriteString("\treturn resp, nil\n}\n\n")
		}

		filePath := filepath.Join(outputDir, fmt.Sprintf("%s.go", strings.ToLower(className)))
		if err := os.WriteFile(filePath, []byte(builder.String()), 0644); err != nil {
			return err
		}
	}

	return nil
}

func generatedOutputDir() (string, error) {
	_, filePath, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("failed to resolve generator path")
	}
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(filePath), "..", ".."))
	return filepath.Join(repoRoot, "pkg", "msfrpc", "generated"), nil
}

func buildArgsString(args []string) string {
	return "[]interface{}{" + strings.Join(args, ", ") + "}"
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}
